### ISSUE TITLE
Getting started repo

### ISSUE THREAD

**Issue by floriansiepe** [quarkiverse/quarkiverse-cxf#100]
It would be beneficial (especially for new users) to have sample or getting started repository for quickly getting started with CXF on Quarkus. Even for those, who are already familiar with CXF could use this as a reference.

However, I stumbled about this since I am not very familiar with CXF. While getting a working application in JVM mode was quite easy, I was not able to get a working native compilation.

**Comment by dufoli** [comment]
you can check integration-test folder

**Comment by dufoli** [comment]
https://github.com/quarkiverse/quarkiverse-cxf/tree/master/integration-tests/

**Comment by floriansiepe** [comment]
Of course. Stupid me. Thanks a lot
