### ISSUE TITLE
release pipeline

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkiverse-cxf#11]
- Publish first release 
- create a RELEASE.MD to document the process
- create roadmap for support to maven central or nexus.

**Comment by shumonsharif** [comment]
@gastaldi I ran a release that got staged to Sonatype Nexus.  Is there some additional process we need to follow to get the artifacts published and/or released to maven central?  Do you manage this process, or should we have access to the Nexus staging repo?

**Comment by gastaldi** [comment]
@shumonsharif the Sonatype Nexus should automatically sync with central after some minutes

**Comment by gastaldi** [comment]
I see it's already there: https://repo1.maven.org/maven2/io/quarkiverse/cxf/quarkus-cxf/0.1.0/

Good job!

**Comment by shumonsharif** [comment]
Thanks so much @gastaldi , just noticed that too, on here:
https://search.maven.org/artifact/io.quarkiverse.cxf/quarkus-cxf/0.1.0/jar

I'll wrap up the rest of the tasks and close out this issue later today.

**Comment by dufoli** [comment]
I have publish all issue to have a kind of roadmap ;-)
