### ISSUE TITLE
add to extension catalog

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkiverse-cxf#16]
here is the git, we have to register an MR to be listed in:
https://github.com/quarkusio/quarkus-extension-catalog

**Comment by dufoli** [comment]
pull request done

**Comment by dufoli** [comment]
on https://github.com/quarkusio/quarkus-extension-catalog/pull/2

**Comment by Dufgui** [comment]
It’s merged

**Comment by shumonsharif** [comment]
@Dufgui @dufoli Are we actually listed in any public catalog?  I thought this would get us listed here:  https://code.quarkus.io/ - but I don't see anything when searching for cxf?

**Comment by dufoli** [comment]
we appear in https://registry.quarkus.io/ which is used by quarkus client if I understood corectly.
I do not know if we will appear on codes.quarkus.io maybe on next release because there is a sync at this moment.
