### ISSUE TITLE
support HTTP Basic auth in outgoing SOAP requests

### ISSUE THREAD

**Issue by bnazare** [quarkiverse/quarkiverse-cxf#43]
Sending the HTTP Basic authentication header during SOAP requests is a fairly common requirement. I propose this functionality be added to the clients generated by quarkiverse-cxf.

In practice, `JaxWsProxyFactoryBean` already exposes the required methods to set the username and password. So this would be just a matter of exposing appropriate configuration parameters and forwarding the values to the relevant methods. I think I could try to create a PR for this, if you're interested.

**Comment by dufoli** [comment]
@bnazare thanks!
