### ISSUE TITLE
CDI Injections not working

### ISSUE THREAD

**Issue by stgiaf** [quarkiverse/quarkiverse-cxf#52]
Hello,
It seems that cdi injected beans are always null in the Implemention classes. 
Is this according to design or a bug?

**Comment by dufoli** [comment]
Are you injecting in something load by the container (REST API,...) or a main ?

https://github.com/quarkiverse/quarkiverse-cxf#creating-a-soap-client

IF you need a main with no exit, read 
https://quarkus.io/guides/command-mode-reference
https://quarkus.io/guides/lifecycle#the-main-method

if you use a command line mode:
https://quarkus.io/guides/picocli

if you need script with maven gradle :
https://quarkus.io/guides/scripting

**Comment by stgiaf** [comment]
Thank you for answer!
I am injecting in a cxf endpoint (server not client) and it always stays null. I manually loaded the class through the CDI class and it worked, but not with the @Inject in the class. So normal injection in a cxf endpoint is not working. Maybe I can create a small project so that it is clearer.

**Comment by dufoli** [comment]
sure because client is injected but server is  not injected. Container run our own servlet. Why do you need to inject servlet ?
Just add your webservice class and setup the application properties and server will run.

**Comment by stgiaf** [comment]
> sure because client is injected but server is not injected. Container run our own servlet. Why do you need to inject servlet ?
> Just add your webservice class and setup the application properties and server will run.

I am trying to inject reactive @Channel so that I can push messages from the cxf endpoint to a message broker. 
I hope I understood your question right..

**Comment by neXus1987** [comment]
i guess injecting within a cxf not working:

```
@WebService(endpointInterface = "service.UserWebservice")
public class UserWebserviceImpl implements UserWebservice {
	
	//not working -> always null
	@Inject
	DummyService dummyService;
	@Override
	public Set<User> listUser() {
		
		//working
		dummyService=CDI.current().select(DummyService.class).get();
		return new HashSet<User>();
	}
}
```

**Comment by stgiaf** [comment]
> i guess injecting within a cxf not working:
> 
> ```
> @WebService(endpointInterface = "service.UserWebservice")
> public class UserWebserviceImpl implements UserWebservice {
> 	
> 	//not working -> always null
> 	@Inject
> 	DummyService dummyService;
> 	@Override
> 	public Set<User> listUser() {
> 		
> 		//working
> 		dummyService=CDI.current().select(DummyService.class).get();
> 		return new HashSet<User>();
> 	}
> }
> ```
> 

Absolutely. This is exactly the case.

**Comment by dufoli** [comment]
ok thanks for example. I will investiguate.

**Comment by dufoli** [comment]
pretty easy fix indeed, I have to change Webservice annotation target as a unremovable bean.

**Comment by dufoli** [comment]
The WebService implementation is not in the jar. Adding @Unremovable resolves this, however would it make sense to include them automatically if they are annotated @WebService? I note that you are currently not looking for this annotation and requiring quarkus.cxf.endpoint."xxx".implementor=SomeClass instead.

 => copy past the need from #82 because it is exactly the same fix.
