### ISSUE TITLE
Split buildtime and runtime config

### ISSUE THREAD

**Issue by dmn1k** [quarkiverse/quarkiverse-cxf#55]
To support multiple environments (like test, staging, production) with a single image, endpoints have to be overridable at runtime. My tests suggest that this is not possible right now:

```
my.service.endpoint=http://localhost:8080
quarkus.cxf.endpoint."/MyService_V_1".client-endpoint-url=${SERVICE_ENDPOINT_URL:${my.service.endpoint}}
```

Setting SERVICE_ENDPOINT_URL at runtime doesnt change the effective value (being the localhost-default).

**TODO:**

- split buildtime and runtime config
- use processor to register SyntheticBeanBuildItem to configure the client.
- add constructor in CxfClientProducer with runtime config param and store it on private field

remarque check mongo code pattern:
https://github.com/quarkusio/quarkus/blob/master/extensions/mongodb-client/deployment/src/main/java/io/quarkus/mongodb/deployment/MongoClientProcessor.java#L265

**Comment by dufoli** [comment]
a very good point. 
Currently all config is handle at build time. We hae to split runtime v buildtime config.
Mongo extension have a such process.
I think to username and password too ;-)
