### ISSUE TITLE
Method not found when using boolean

### ISSUE THREAD

**Issue by neXus1987** [quarkiverse/quarkiverse-cxf#70]
Hi,

on native mode i got the error Method not found for, e.g. getNormal(), so the method is called isNormal() because it is a boolean.
On jvm mode this will work. This is a POJO used by an Endpoint.

Or Should i switch to getNormal() for boolean values?

Thanks

**Comment by neXus1987** [comment]
when using getNormal() this will work, but the wsdl generator generates isNormal()

**Comment by dufoli** [comment]
in webservice method or in wrapper  ?

**Comment by neXus1987** [comment]
This is in wrapper (i have changed it to getXXXX), so there exist also a plugin from apache cxf which generates getXXXX for booleans)

**Comment by dufoli** [comment]
oh yes all wrapper expect a name with get or set.
https://github.com/apache/cxf/blob/837401d8b08449ea34304df68600514d1132c499/core/src/main/java/org/apache/cxf/common/jaxb/JAXBUtils.java#L535
so it come from cxf...

**Comment by neXus1987** [comment]
yes exactly, i guess so we can close this issue.
