### ISSUE TITLE
Native compilation fails when using request/response wrapper with elements not in camel case

### ISSUE THREAD

**Issue by bnazare** [quarkiverse/quarkiverse-cxf#78]
I have generated Java code from a third-party WSDL. The generate code makes extensive use of response/request wrappers. One of the response wrappers looks like this (slightly trimmed down):

```java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scmdSignResult"
})
@XmlRootElement(name = "SCMDSignResponse")
public class SCMDSignResponse {

    @XmlElementRef(name = "SCMDSignResult", namespace = "http://Ama.Authentication.Service/", type = JAXBElement.class, required = false)
    protected JAXBElement<SignStatus> scmdSignResult;

    public JAXBElement<SignStatus> getSCMDSignResult() {
        return scmdSignResult;
    }

    public void setSCMDSignResult(JAXBElement<SignStatus> value) {
        this.scmdSignResult = value;
    }

}
```

Notice the differences between the field name, the XML element name in the annotation and the getter/setter names.

When I try to compile my application natively I get the following exception:
```
com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: service.authentication.ama.SCMDSignResponse.setScmdSignResult(javax.xml.bind.JAXBElement). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
```

It seems clear that such error occurs because the code is trying to call `setScmdSignResult()` instead of `setSCMDSignResult()` which has different capitalization. The root cause seems to be that the extension code is trying to derive the setter name from the field name which, at this point, has already lost most of the capitalization information. Instead, it should probably look at the `@XmlElementRef` annotation and use its value if present.

**Comment by bnazare** [comment]
I forgot to add that this also impacts the discovery of "create" methods in the `ObjectFactory`.
For example, in this case the related method is `createSCMDSignResponseSCMDSignResult()` but instead `createSCMDSignResponseScmdSignResult()` would be called.

#79 covers both those issues.

**Comment by dufoli** [comment]
Can you give me the scmdSignResult or an equivalent to add a test with jaxbelement and wrapper annotation

**Comment by bnazare** [comment]
> Can you give me the scmdSignResult or an equivalent to add a test with jaxbelement and wrapper annotation

You mean the class used as the type of `scmdSignResult`, meaning `SignStatus`?

Unfortunately, I don't think the service provider will take it ligthy to me sharing too much of their schemas and namespaces in GitHub. Even if the WSDL is publicly available :/.

On the plus side, I don't think that type actually matters for this issue, so you can probably replace it with `String` and it should break all the same. However, if you take that route and commit it, please also change the namespace to something innocuous like "http://foo.bar/".

If you prefer to wait, I might be able to create a more sanitized version of that code to use for tests but I'll only be able to get to it later tomorrow.

**Comment by dufoli** [comment]
no problem, I will do my own class of jaxbElement for a unit test. Else I will take one from cxf unit test.

**Comment by dufoli** [comment]
I have merge your pull request but After that, I was thinking that maybe I must based my code in method and not field name:

```
for (Method m : wrapperClass.getDeclaredMethods()) {
                                if (m.getParameterCount() == 0 && (m.getName().startsWith("get") || m.getName().startsWith("is"))) {
                                    getters.add(MethodDescriptor.ofMethod(fullClassName,
                                            m.getName(),
                                            m.getReturnType().getName()));
                                    String setterName = m.getName().startsWith("get") ?
                                            "s" + m.getName().substring(1): "set" + m.getName().substring(2);
                                    try {
                                        //check that method exist before add it
                                        wrapperClass.getDeclaredMethod(setterName, m.getReturnType());
                                        setters.add(MethodDescriptor.ofMethod(fullClassName,
                                                setterName, "V",
                                                m.getReturnType().getName()));
                                    } catch (NoSuchMethodException e) {
                                        setters.add(null);
                                    }
                                }
                            }
```

**Comment by dufoli** [comment]
wdyt ?
