### ISSUE TITLE
support XmlSeeAlso annotation

### ISSUE THREAD

**Issue by dufoli** [quarkiverse/quarkiverse-cxf#8]

**Comment by Adelrisk** [comment]
I'd like to give a heads-up of a XmlSeeAlso-related issue in graalvm: https://github.com/oracle/graal/issues/2720 and my willingness to help address it.

Btw, I just stumbled upon this extension - I think it's great, I can't wait to try it out and I'm notifying my team. :+1:

**Comment by dufoli** [comment]
@Adelrisk I have add missing stuff for xmlSeeAlso but I need a real test (unit test is not launched on native) Else I have to produce a real test on integration test...
Anyway, if it work I will propose a patch to jaxb extension with many stuff fixed in cxf. I have already an issue on project to do so.

**Comment by Adelrisk** [comment]
Great work and thanks for the timely feedback!
