### ISSUE TITLE
Port type name is used in place of the service name

### ISSUE THREAD

**Issue by bnazare** [quarkiverse/quarkiverse-cxf#85]
In [this line](https://github.com/quarkiverse/quarkiverse-cxf/blob/8daae3bd3e898c7860025ac32370851e8c775f6d/deployment/src/main/java/io/quarkiverse/cxf/deployment/QuarkusCxfProcessor.java#L1091) the value of attribute `name` from annotation `@WebService` is taken and then in [this line](https://github.com/quarkiverse/quarkiverse-cxf/blob/8daae3bd3e898c7860025ac32370851e8c775f6d/runtime/src/main/java/io/quarkiverse/cxf/CxfClientProducer.java#L35) that value is used to set the service name. This causes errors whenever port type name and service name don't happen to match.

This happens because, in an unintuitive twist, the `name` attribute actually refers to the port type name and the service name is instead in the `serviceName` attribute. You can confirm this in [the javadoc](https://docs.oracle.com/javase/7/docs/api/javax/jws/WebService.html#name()).

To complicate matters further you can't have the `serviceName` attribute in endpoint interfaces (SEIs) and tools like "wsdl2java" won't generate code with it there. More information [here](https://docs.oracle.com/javase/7/docs/api/javax/jws/WebService.html#serviceName()) and [here](http://cxf.547215.n5.nabble.com/wsdl2java-does-not-generate-serviceName-in-WebService-Annotation-td558502.html#a558503).

If you'd like to reproduce the issue, you can use the following configuration, after generating the appropriate classes from the WSDL:
```properties
quarkus.cxf.endpoint."calculator.asmx".wsdl=http://www.dneonline.com/calculator.asmx?wsdl
quarkus.cxf.endpoint."calculator.asmx".client-endpoint-url=http://www.dneonline.com
quarkus.cxf.endpoint."calculator.asmx".service-interface=org.tempuri.CalculatorSoap
quarkus.cxf.endpoint."calculator.asmx".endpoint-namespace=http://tempuri.org/
quarkus.cxf.endpoint."calculator.asmx".endpoint-name=CalculatorSoap
```

A quick fix could be to add two new configuration parameters for the name and namespace of the service (like you have for the endpoint). A more elaborate fix could make use of classes annotated with `@WebServiceClient` which usually contain this information and are readily generated by tools like "wsdl2java".

**Comment by dufoli** [comment]
I will use ServiceName attribute else implementor simple name and if no implementor sei simple name. I prefer convention over configuration ;-)

**Comment by bnazare** [comment]
Hey @dufoli, I tested your changes and they don't work very well :(. According to my tests, when generating a SEI from a WSDL, by default the SEI class will be named accordingly to the port type name so the same problem occurs.

This is not impossible to avoid, if you mess around with JAX-WS binding files (as seen [here](https://cxf.apache.org/docs/wsdl-to-java.html#WSDLtoJava-JAXWSCustomization)). However, this comes with at least two problems: 1) it's arguably more complicated than having configuration options 2) it will make the SEI class have the same name as the `@WebServiceClient` class would have by default, forcing that one to have a procedurally modified name that might be unexpected to users.

**Comment by dufoli** [comment]
Hmm OK so go for configuration... And annotation support.

**Comment by dufoli** [comment]
If you can provide a pr to add test with wsdl génération that can be awesome!

**Comment by dufoli** [comment]
else why not ask cxf to generate the serviceName with wsdl2java tool...

**Comment by bnazare** [comment]
> If you can provide a pr to add test with wsdl génération that can be awesome!

I was actually trying to create something like this when I stumbled on this issue. I might be able to get it ready for a PR early next week.

**Comment by bnazare** [comment]
> else why not ask cxf to generate the serviceName with wsdl2java tool...

As far as I can tell, that option doesn't exist. And according to [this discussion](http://cxf.547215.n5.nabble.com/wsdl2java-does-not-generate-serviceName-in-WebService-Annotation-td558502.html#a558503) it would be against the spec if it did :/.

**Comment by bnazare** [comment]
Hi, so #98 didn't solve this, in fact it made it worse because now I get an empty string as the service name.

To try and break it down, it seems that you assumed that the classes annotated with `@WebServiceClient` are implementors of the SEI which is never the case. In fact, the two classes usually have no hierarchical relation. The only connection between them is that the client class offers methods that return instances of the SEI. I played with the code for a bit and came up with a draft for a method that manages to find the correct `@WebServiceClient` annotation, so here you go:

```java
private AnnotationInstance findWebServiceClientAnnotation(IndexView index, String sei) {
    Collection<AnnotationInstance> annotations = index.getAnnotations(WEBSERVICE_CLIENT);
    for (AnnotationInstance annotation : annotations) {
        ClassInfo targetClass = annotation.target().asClass();

        for (MethodInfo method : targetClass.methods()) {
            if (method.returnType().name().toString().equals(sei)) {
                return annotation;
            }
        }
    }

    return null;
}
```

It should be called for SEIs without implementations. You can add it yourself in a new PR if you'd like. In alternative, I can add it to #97. Let me know what you'd like to do.

Also, please note that there's at least a case where this code will break which is the rare case when two SOAP services exist offering endpoints for the same port type.

**Comment by dufoli** [comment]
hmm, please add it to #97 , at least the code move to the real owner ;-)
it is far too complicated for me because I do not used it. I just do this extension to contribute to quarkus and discover extension at start...

**Comment by dufoli** [comment]
I was thinking that test webserviceClient != null is enough...
Maybe I have to test that webserviceClient.value("name").asString(); is not empty too...

**Comment by dufoli** [comment]
Is is planned to add a config element too.
What do you prefere in order of priority between
- webserviceClient annotation
- sei name
- implementor name
- webService annotation serviceName
- config serviceName

too much possibilitied IMO... but we need a simple rules about which one is taken in priority... Do you know if there is a such thing in specification of jaxws ?

**Comment by bnazare** [comment]
hi @dufoli, for now I added the fix I discussed to #97 (along with some other changes and a rebase). Clunky as it is, it will at least fix this issue for the moment and allowed me to removed the workarounds in #97.

As for the question in your latest comment, I need to think harder and longer about it. I'll get back to you ;).

**Comment by dufoli** [comment]
thank you very much for this patch @bnazare ;-)

**Comment by dufoli** [comment]
@bnazare  I ask to cxf for that with https://issues.apache.org/jira/browse/CXF-8409
I talked to 3 maintainer of the cxf team for the graalvm support. So I guess they will help now they know me ;-)

**Comment by bnazare** [comment]
Hi @dufoli, here's my thoughts on this:
- I think the SEI is pretty much useless in this matter. By convention, its name should reference the port type name and not the service name. And even when it has the `@WebService`, the spec disallows it from specifying the `serviceName` attribute. So neither value is usable here.
- Services and clients should be treated separetely in this matter since they use distinct mechanisms to specify their metadata:
  - Services have their information in the implementor class (and its annotations)
  - Clients may have their information in the client class (the one annotated with `@WebServiceClient`)
- For a service class we should preferably take the values from the attributes `targetNamespace` and `serviceName` in the implementor's `@WebService` annotation, if available. It not, we should derive them from the the implementor's package and class names. I'm not absolutely sure but I think this is the default behaviour of JAX-WS/CXF so maybe there's nothing do implement in this regard. We could add a configuration option but since the users will have total control of the implementator's code that sounds redundant.
- For clients, we can take the values from the correspondent `@WebServiceClient` annotation when available. Its presence is an almost certainty when generating client code from a WSDL but very doubtful if a user is creating the code by hand. When the annotation is not present, I don't think there's any other option than using a configuration option. If you want to simplify it though, you can allow the configuration of both the service's namespace and name with a single property by accepting the same format as [`QName.valueOf()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/namespace/QName.html#valueOf(java.lang.String)).
