### ISSUE TITLE
How to config a two way SSL consuming webservice?

### ISSUE THREAD

**Issue by CarlosPanarello** [quarkiverse/quarkiverse-cxf#89]
How to config CXF to send a request to a webservice for two way SSL connection?

I look in the [docs of Apache CXF](https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html#ClientHTTPTransport(includingSSLsupport)-ConfiguringSSLSupport), there they have some xml to config , but how this will be in the application.properties?

**Comment by dufoli** [comment]
the extension use the vertx routing so can you check with this setup
[https://quarkus.io/guides/http-reference](https://quarkus.io/guides/http-reference)

**Comment by CarlosPanarello** [comment]
I solved using an Interceptor to add keystore and truststore in the request.
